# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='currently_waiting',
            field=models.BooleanField(default='False'),
        ),
    ]
