# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_currently_waiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
    ]
