# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170731_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_game',
        ),
        migrations.AddField(
            model_name='game',
            name='black_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='white_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='game.Player'),
        ),
    ]
