# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170731_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_game',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
    ]
