# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20170830_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fen',
            field=models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100),
        ),
    ]
