# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20170830_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_over',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='White to move', max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='pgn',
            field=models.CharField(default='', max_length=300),
        ),
    ]
