# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20170831_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_draw_offered',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='game',
            name='white_draw_offered',
            field=models.BooleanField(default='False'),
        ),
    ]
