# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20170831_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='black_draw_offered',
        ),
        migrations.RemoveField(
            model_name='game',
            name='white_draw_offered',
        ),
        migrations.AddField(
            model_name='game',
            name='draw_offered',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='player',
            name='opponent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
    ]
