# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20170831_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='opponent',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='currently_waiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='in_game',
            field=models.BooleanField(default=False),
        ),
    ]
